server:
  port: 8801

manange:
  port: 8802

spring:
  application:
    name: turbine

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

turbine:
  app-config: ribbon-consumer,ribbon-consumer-1
  cluster-name-expression: new String('default')
  combine-host-port: true