server:
  port: 8800

manange:
  port: 8801

spring:
  application:
    name: turbine

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

turbine:
  app-config: ribbon-consumer,ribbon-consumer-1
  cluster-name-expression: new String('default')
  combine-host-port: true