server:
  port: 8831

spring:
  rabbitmq:
    host: 172.16.5.30
    port: 5672
    username: admin
    password: Dah10oo00+1
  security:
    user:
      name: admin
      password: admin
  application:
    name: config-server
#  从本地存储读取配置，默认从应用的src/main/resource目录下检索配置文件
  profiles:
    active: native
#    cloud:
#      config:
#        server:
#          native: #加载本地目录文件
#            search-locations: /Users/xxxx/config-server
#  cloud:
#    config:
#      server:
#        git:
#          uri: git@github.com:VodkaAddict/MySpringCloud.git
#          search-paths: config-repository
#          skip-ssl-validation: true
#          username: VodkaAddict
#          password:
  cloud:
    bus:
      trace:
        enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
